# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: cf-exporter

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: default
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
      - -X main.name={{.ProjectName}}
      - -X main.version={{.Version}}
      - -X main.date={{.Date}}
      - -X main.gitCommit={{.ShortCommit}}
      - -X main.gitState={{.GitTreeState}}
      - -X main.builtBy=goreleaser

archives:
  - id: default
    builds:
      - default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    strip_binary_directory: true
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

dockers:
  - id: default-amd64
    ids:
      - default
    use: buildx
    goos: linux
    goarch: amd64
    skip_push: false
    image_templates:
      - "ghcr.io/kamontat/cloudflare-exporter:amd64"
      - "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.tag={{.Tag}}"
      - "--platform=linux/amd64"
  - id: default-arm64
    ids:
      - default
    use: buildx
    goos: linux
    goarch: arm64
    skip_push: false
    image_templates:
      - "ghcr.io/kamontat/cloudflare-exporter:arm64"
      - "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.tag={{.Tag}}"
      - "--platform=linux/arm64/v8"
  - id: default-armv6
    ids:
      - default
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    skip_push: false
    image_templates:
      - "ghcr.io/kamontat/cloudflare-exporter:armv6"
      - "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}-armv6"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.tag={{.Tag}}"
      - "--platform=linux/arm/v6"
  - id: default-armv7
    ids:
      - default
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    skip_push: false
    image_templates:
      - "ghcr.io/kamontat/cloudflare-exporter:armv7"
      - "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}-armv7"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.tag={{.Tag}}"
      - "--platform=linux/arm/v7"
docker_manifests:
  - name_template: "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}"
    image_templates:
      - "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}-amd64"
      - "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}-arm64"
      - "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}-armv7"
      - "ghcr.io/kamontat/cloudflare-exporter:{{.Version}}-armv6"
  - name_template: "ghcr.io/kamontat/cloudflare-exporter:latest"
    image_templates:
      - "ghcr.io/kamontat/cloudflare-exporter:amd64"
      - "ghcr.io/kamontat/cloudflare-exporter:arm64"
      - "ghcr.io/kamontat/cloudflare-exporter:armv7"
      - "ghcr.io/kamontat/cloudflare-exporter:armv6"

report_sizes: true

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

# TODO: implement sign binary and docker image
# binary_signs:
#   - {}
# signs:
#   - artifacts: checksum

snapshot:
  version_template: "{{.Version}}-dev.{{.ShortCommit}}"
release:
  ## Generated from release-please
  mode: keep-existing
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
