
query TestQuery() {
  viewer {
    zones(limit: 10, filter: {zoneTag: "174fbdbf05250df2b075786311ed0d22"}) {
      httpRequests1mGroups(limit: 2, filter: {datetimeHour: "2024-08-17T10:00:00Z"}) {
        avg {
          bytes
          sampleInterval
        }
      }
    }
  }
}
