# Default genqlient config; for full documentation see:
# https://github.com/Khan/genqlient/blob/main/docs/genqlient.yaml

schema: ../schema.gql
operations:
  - ../queries/*.gql
generated: ../graphql-query.gen.go

bindings:
  string:
    type: string
  uint64:
    type: uint64
  float64:
    type: float64
  Time:
    type: time.Time
