// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package cloudflare

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// ZonesRequestsTotalResponse is returned by ZonesRequestsTotal on success.
type ZonesRequestsTotalResponse struct {
	Viewer ZonesRequestsTotalViewer `json:"viewer"`
}

// GetViewer returns ZonesRequestsTotalResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalResponse) GetViewer() ZonesRequestsTotalViewer { return v.Viewer }

// ZonesRequestsTotalViewer includes the requested fields of the GraphQL type viewer.
type ZonesRequestsTotalViewer struct {
	Zones []ZonesRequestsTotalViewerZonesZone `json:"zones"`
}

// GetZones returns ZonesRequestsTotalViewer.Zones, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewer) GetZones() []ZonesRequestsTotalViewerZonesZone { return v.Zones }

// ZonesRequestsTotalViewerZonesZone includes the requested fields of the GraphQL type zone.
type ZonesRequestsTotalViewerZonesZone struct {
	ZoneTag string `json:"zoneTag"`
	// Aggregated HTTP requests data with adaptive sampling
	Requests []ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups `json:"requests"`
}

// GetZoneTag returns ZonesRequestsTotalViewerZonesZone.ZoneTag, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZone) GetZoneTag() string { return v.ZoneTag }

// GetRequests returns ZonesRequestsTotalViewerZonesZone.Requests, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZone) GetRequests() []ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups {
	return v.Requests
}

// ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups includes the requested fields of the GraphQL type ZoneHttpRequestsAdaptiveGroups.
// The GraphQL type's documentation follows.
//
// Aggregated HTTP requests data with adaptive sampling
type ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups struct {
	// The number of values for a metric per dimension
	Count uint64 `json:"count"`
	// The sum of values for a metric per dimension
	Sum ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsSum `json:"sum"`
	// The average value used for sample interval
	Avg ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsAvg `json:"avg"`
}

// GetCount returns ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups.Count, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups) GetCount() uint64 {
	return v.Count
}

// GetSum returns ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups.Sum, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups) GetSum() ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsSum {
	return v.Sum
}

// GetAvg returns ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups.Avg, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroups) GetAvg() ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsAvg {
	return v.Avg
}

// ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsAvg includes the requested fields of the GraphQL type ZoneHttpRequestsAdaptiveGroupsAvg.
type ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsAvg struct {
	// The average originResponseDuration, in milliseconds, excluding 0 values (i.e. cached ones)
	OriginResponseDurationMs float64 `json:"originResponseDurationMs"`
	EdgeDnsResponseTimeMs    float64 `json:"edgeDnsResponseTimeMs"`
}

// GetOriginResponseDurationMs returns ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsAvg.OriginResponseDurationMs, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsAvg) GetOriginResponseDurationMs() float64 {
	return v.OriginResponseDurationMs
}

// GetEdgeDnsResponseTimeMs returns ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsAvg.EdgeDnsResponseTimeMs, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsAvg) GetEdgeDnsResponseTimeMs() float64 {
	return v.EdgeDnsResponseTimeMs
}

// ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsSum includes the requested fields of the GraphQL type ZoneHttpRequestsAdaptiveGroupsSum.
type ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsSum struct {
	// The number of requests by end-users that were initiated from a different website (i.e. where the request HTTP Referer header does not match the host in the HTTP Host header)
	Visits            uint64 `json:"visits"`
	EdgeResponseBytes uint64 `json:"edgeResponseBytes"`
}

// GetVisits returns ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsSum.Visits, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsSum) GetVisits() uint64 {
	return v.Visits
}

// GetEdgeResponseBytes returns ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsSum.EdgeResponseBytes, and is useful for accessing the field via an interface.
func (v *ZonesRequestsTotalViewerZonesZoneRequestsZoneHttpRequestsAdaptiveGroupsSum) GetEdgeResponseBytes() uint64 {
	return v.EdgeResponseBytes
}

// __ZonesRequestsTotalInput is used internally by genqlient
type __ZonesRequestsTotalInput struct {
	Zones []string  `json:"zones"`
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

// GetZones returns __ZonesRequestsTotalInput.Zones, and is useful for accessing the field via an interface.
func (v *__ZonesRequestsTotalInput) GetZones() []string { return v.Zones }

// GetStart returns __ZonesRequestsTotalInput.Start, and is useful for accessing the field via an interface.
func (v *__ZonesRequestsTotalInput) GetStart() time.Time { return v.Start }

// GetEnd returns __ZonesRequestsTotalInput.End, and is useful for accessing the field via an interface.
func (v *__ZonesRequestsTotalInput) GetEnd() time.Time { return v.End }

// The query or mutation executed by ZonesRequestsTotal.
const ZonesRequestsTotal_Operation = `
query ZonesRequestsTotal ($zones: [string!]!, $start: Time!, $end: Time!) {
	viewer {
		zones(filter: {zoneTag_in:$zones}) {
			zoneTag
			requests: httpRequestsAdaptiveGroups(limit: 1, filter: {requestSource:"eyeball",datetime_geq:$start,datetime_lt:$end}) {
				count
				sum {
					visits
					edgeResponseBytes
				}
				avg {
					originResponseDurationMs
					edgeDnsResponseTimeMs
				}
			}
		}
	}
}
`

func ZonesRequestsTotal(
	ctx_ context.Context,
	client_ graphql.Client,
	zones []string,
	start time.Time,
	end time.Time,
) (*ZonesRequestsTotalResponse, error) {
	req_ := &graphql.Request{
		OpName: "ZonesRequestsTotal",
		Query:  ZonesRequestsTotal_Operation,
		Variables: &__ZonesRequestsTotalInput{
			Zones: zones,
			Start: start,
			End:   end,
		},
	}
	var err_ error

	var data_ ZonesRequestsTotalResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
