name: Main

on:
  push:

# concurrency:
#   cancel-in-progress: true
#   group: main-${{ github.ref }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up code
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Tidy go module
        run: go mod tidy
      - name: Generate go module
        run: go generate ./...
      - name: Check GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: check
      - name: Build application
        uses: goreleaser/goreleaser-action@v6
        with:
          args: build --clean
