name: Release

on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: release-${{ github.ref }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create release pull-request
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: .github/configs/release-please-config.json
          manifest-file: .github/configs/.release-please-manifest.json
